### ISSUE TITLE
migrate to google analytic 4

### ISSUE THREAD

**Issue by alexskr** [ncbo/bioportal-project#248] opened 2022-06-28 17:07 UTC
Google Analytics 4 is replacing Universal Analytics. On July 1, 2023, Universal Analytics properties will stop processing new hits. 

https://support.google.com/analytics/answer/10759417

**Comment by syphax-bouazzouni** [comment] 2023-05-03 19:58
Pinging @gturrisi-lifewatch as they are also working on this at Ecoportal.

**Comment by jvendetti** [comment] 2023-06-26 19:34
The necessary changes to support GA4 in the Rails application have been implemented / merged. See https://github.com/ncbo/bioportal_web_ui/pull/271.

If I navigate to analytics.google.com and look at the "BioPortal - GA4" property, there's a message at the top of the page about setup completion:

<img width="831" alt="Screen Shot 2023-06-26 at 12 32 26 PM" src="https://github.com/ncbo/bioportal-project/assets/1696923/1d18d393-dab8-4631-89f4-721f9fa2f182">
<br><br>

Not sure if anything else is needed from me for this task?

**Comment by graybeal** [comment] 2023-06-29 02:50
Please create and work with team to assign appropriate tickets for each of the subtasks needed to complete our transition to GAv4. (You may wish to change this ticket to an Epic or equivalent, to make it easier to track its subitems.)

**Comment by mdorf** [comment] 2023-07-07 20:19
Google Analytics V1 Data (GA4) no longer supports filtering on the referrers domain names. The issue is described in detail in this doc:
https://www.idimension.com/2020/02/google-analytics-no-longer-supports-service-provider-and-network-domain-dimensions/

Below is the reference documentation for the various dimensions and metrics that exist in GA4:
https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema

Alternatives do exist, but they don't appear to be trivially implemented. I will remove this filter for now in the new code that supports GA4.

**Closed as completed** 2024-10-04 22:43 UTC
