### ISSUE TITLE
mappings display has duplicates

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#69] opened 2018-03-08 20:46 UTC
Mark writes:
And the display of mappings now shows everything duplicated for every term I look at ...

![PastedGraphic-1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56faf7f8d928b91300aff9d1/125516c66e82c728ace21e0d46d895893787878e9de8af4bad5ebdc56b0a65633b0ba92e7391a172fd1723580e584caf480a5744aeabd823a1b63c71820a0ebc857f4366846c4ff8e7df46f554f832815d84bfb68b49c2e83821e58a8c4e3b16060ac4.png)

**Comment by graybeal** [comment] 2018-03-08 20:53
And this was sent to Mark:

Subject: NCBO BioPortal ontology mapping issue

<snip> As discuss, please find below the link to the term with one to two mapping from ICD-10 to SNOMED CT

https://bioportal.bioontology.org/ontologies/ICD10/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FICD10%2FO45.9

I hope to learn about resolving the mapping of this.

**Comment by jvendetti** [comment] 2018-03-08 21:30
@graybeal - I looked at the URL you provided in the last comment (from end user Phan H.T.T.), where he claims there are incorrect one to two mappings from ICD-10 to SNOMEDCT.

It's my impression that BioPortal is behaving as designed because it created mappings between the source class, and two destination classes in SNOMEDCT that all have the same CUI values.

The class selected on the left-hand side is "Premature separation of placenta, unspecified". There are two mappings listed on the right-hand side to SNOMEDCT classes. One of them is "Placental abruption", and the other is "Accidental antepartum hemorrhage". Both of the SNOMEDCT classes have the same CUI values, but they have different SNOMED IDs and are distinct. I've listed it out more concretely below:

**Source class (left-hand side)**
```
Preferred name: Premature separation of placenta, unspecified
CUI: C0000832
```

**Mapped classes (right-hand side)**

```
Preferred name: Placental abruption 
CUI: C0000832
SNOMED ID: D8-0012A

Preferred name: Accidental antepartum hemorrhage
CUI: C0000832
SNOMED ID: D8-1022C
```

This end user complaint doesn't appear to be valid to me.

**Comment by jvendetti** [comment] 2018-03-08 21:38
In the case of the first comment with a screenshot of the FMA ontology, it's not immediately obvious to me why duplicates appear to be listed. We don't have anyone on the current team that knows the mapping code. It would likely take some effort to understand the underlying issue here.

**Comment by graybeal** [comment] 2018-03-09 00:29
Well, "I am not a doctor", but Google confirms my suspicion that this report is one of those approximate mappings. "Accidental antepartum hemorrhage" _could be_  a separation of the placenta, or could be bleeding from something else. So it's just not a very clean match, which might have triggered the user's concern. I agree that the screenshot is the only issue, and see if I can identify any reason for it.

**Comment by graybeal** [comment] 2018-06-18 23:39
Here's another case, slightly different.  In HP, there are 10 mappings for 'retinoblastoma' to MONDO. The odd bit is that all 10 have the same URI in MONDO (http://purl.obolibrary.org/obo/MONDO_0003078). 

This almost makes some sense for LOOM mappings. If I look for retinoblastoma in the preferred label, there are 12 entries that have it. But 12 isn't 10, and why wouldn't it show the correct unique identifiers?
```
http://purl.obolibrary.org/obo/MONDO_0003076 | unilateral retinoblastoma
http://purl.obolibrary.org/obo/MONDO_0003074 | familial retinoblastoma
http://purl.obolibrary.org/obo/MONDO_0003075 | bilateral retinoblastoma
http://purl.obolibrary.org/obo/MONDO_0003077 | intraocular retinoblastoma
http://purl.obolibrary.org/obo/MONDO_0003073 | trilateral retinoblastoma
http://purl.obolibrary.org/obo/MONDO_0018161 | non-hereditary retinoblastoma
http://purl.obolibrary.org/obo/MONDO_0018160 | hereditary retinoblastoma
http://purl.obolibrary.org/obo/MONDO_0004350 | pediatric extraocular retinoblastoma
http://purl.obolibrary.org/obo/MONDO_0010630 | imprinting gene related to retinoblastoma
http://purl.obolibrary.org/obo/MONDO_0008380 | retinoblastoma
http://purl.obolibrary.org/obo/MONDO_0003078 | extraocular retinoblastoma
http://purl.obolibrary.org/obo/MONDO_0004045 | pediatric intraocular retinoblastoma
```

I think we're going to have to look at the exact code and exact SPARQL to figure it out.

**Comment by jvendetti** [comment] 2019-10-04 19:09
Duplicate display of mapping tables in mapping dialogs is fixed (see: https://github.com/ncbo/bioportal_web_ui/issues/103).

With regard to the other problem report, new versions of HP and MONDO have been uploaded to BioPortal such that HP no longer contains 10 mappings for 'retinoblastoma' to MONDO. Closing this issue for now, as we have no reproducible example where the backend returns duplicate mappings for a term.

**Closed by jvendetti** 2019-10-04 19:09 UTC
Labels: in progress
