### ISSUE TITLE
NCBO BioPortal Appliance AMI

### ISSUE THREAD

**Issue by jvendetti** [ncbo/bioportal-project#15] opened 2017-03-24 02:12 UTC
Reported by @gibiceh:

I apologize if this is the wrong forum for this question. If this is the wrong forum, I would appreciate any assistance in pointing me to the correct support forum.

I recently installed version 2.4 of the NCBO BioPortal Appliance AMI on a m3.large aws ec2 instance. After uploading an ontology via an OWL file, I noticed that "Loading" messages would persist when accessing the Classes and Properties tabs of the ontology. This behavior was seen for both the standard default ontology packaged with the AMI and the ontology that I supplied. It would take a page refresh in order to load the content of these tabs. Is it known how to remedy this behavior.

In addition, I noticed that version 2.3 of the appliciance was available as an AMI on aws. I installed this version on the same instance type and was successfully able to access the Classes tab for both my provided ontology and the pre-packaged ontology that came with the appliance. However I did not see where Properties could be viewed. Are Properties unable to be viewed in version 2.3, or is there a setting that needs to be enabled in order to view them.

Thank you so much for any help provided and please let me know if any further information would help answer my inquiry.

**Comment by graybeal** [comment] 2017-03-24 02:48
Unfortunately, we are not aware of this problem occurring with other AMI installations, and do not know of a fix at this time. I'm going to copy this problem to the support list (support@bioontology.org) to see if anyone else has come across it.

Based on the timing of the Properties UI and the Virtual Appliance 2.4 release (just afterwards), I am confident the Properties UI was not in the Virtual Appliance 2.3. You may be able to access them via the API, I am not sure.

I am leaving this issue open for now, pending obtaining more information from the user as to whether it is a critical issue in the short term. We will be working on a new Virtual Appliance release in coming months, which should make this issue moot at that point.

**Comment by graybeal** [comment] 2019-08-10 23:08
duplicate of bioportal_web_ui#42

**Closed by graybeal** 2019-08-10 23:08 UTC
Labels: Virtual Appliance
