### ISSUE TITLE
Visualization not working?

### ISSUE THREAD

**Issue by graybeal** [ncbo/bioportal-project#67] opened 2018-03-08 20:31 UTC
Mark writes 3/4/18: 
Clicking on “visualization” no longer seems to do anything, at least for the ontologies that I tried.

**Comment by jvendetti** [comment] 2018-03-08 20:45
There's a known issue with the BioMixer application (developed by the University of Victoria) that produces the visualizations. It doesn't work over HTTPS. Details here: https://github.com/ncbo/biomixer/issues/2.

If Mark changes the URL in the address bar to use HTTP, the visualizations show without problems. For example, entering the following URL:

http://bioportal.bioontology.org/ontologies/SNOMEDCT/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FSNOMEDCT%2F404684003#visualization

... results in the ability to see the visualization:

![screenshot 2018-03-08 12 42 29](https://user-images.githubusercontent.com/1696923/37175390-3ead1e7a-22ce-11e8-8bae-5fd97c8f176a.png)

Closing this as a duplicate of the above mentioned issue, entered against the BioMixer codebase.

**Closed by jvendetti** 2018-03-08 20:45 UTC
Labels: duplicate
